spring:
    application:
        name: mind-link

    datasource:
        url: jdbc:mysql://localhost:3306/mind-link
        username: root
        password: adminadmin
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
    secret: "mY7vL9j8q2KxP4sE1uR0nD6hT3cB5fG8yH1kM2wQ9pV7zX0aL4" # almeno 48 caratteri
    expiration: 3600000 # durata token in ms (1 ora)